/**
 * generated by Xtext 2.25.0
 */
package org.xtext.idmProject.iDMProject;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.idmProject.iDMProject.Insert#getPath <em>Path</em>}</li>
 *   <li>{@link org.xtext.idmProject.iDMProject.Insert#getJsonInString <em>Json In String</em>}</li>
 * </ul>
 *
 * @see org.xtext.idmProject.iDMProject.IDMProjectPackage#getInsert()
 * @model
 * @generated
 */
public interface Insert extends Operation
{
  /**
   * Returns the value of the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' containment reference.
   * @see #setPath(Path)
   * @see org.xtext.idmProject.iDMProject.IDMProjectPackage#getInsert_Path()
   * @model containment="true"
   * @generated
   */
  Path getPath();

  /**
   * Sets the value of the '{@link org.xtext.idmProject.iDMProject.Insert#getPath <em>Path</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' containment reference.
   * @see #getPath()
   * @generated
   */
  void setPath(Path value);

  /**
   * Returns the value of the '<em><b>Json In String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Json In String</em>' attribute.
   * @see #setJsonInString(String)
   * @see org.xtext.idmProject.iDMProject.IDMProjectPackage#getInsert_JsonInString()
   * @model
   * @generated
   */
  String getJsonInString();

  /**
   * Sets the value of the '{@link org.xtext.idmProject.iDMProject.Insert#getJsonInString <em>Json In String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Json In String</em>' attribute.
   * @see #getJsonInString()
   * @generated
   */
  void setJsonInString(String value);

} // Insert
