/**
 * generated by Xtext 2.25.0
 */
package org.xtext.idmProject.iDMProject;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Commands</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.idmProject.iDMProject.JsonCommands#getJsonCommands <em>Json Commands</em>}</li>
 * </ul>
 *
 * @see org.xtext.idmProject.iDMProject.IDMProjectPackage#getJsonCommands()
 * @model
 * @generated
 */
public interface JsonCommands extends EObject
{
  /**
   * Returns the value of the '<em><b>Json Commands</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.idmProject.iDMProject.JsonCommand}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Json Commands</em>' containment reference list.
   * @see org.xtext.idmProject.iDMProject.IDMProjectPackage#getJsonCommands_JsonCommands()
   * @model containment="true"
   * @generated
   */
  EList<JsonCommand> getJsonCommands();

} // JsonCommands
