/**
 * generated by Xtext 2.25.0
 */
package org.xtext.idmProject.iDMProject;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Object</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.idmProject.iDMProject.IDMProjectPackage#getJsonObject()
 * @model
 * @generated
 */
public interface JsonObject extends EObject
{
} // JsonObject
