/**
 * generated by Xtext 2.25.0
 */
package org.xtext.idmProject.iDMProject;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Print</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.idmProject.iDMProject.IDMProjectPackage#getPrint()
 * @model
 * @generated
 */
public interface Print extends Final
{
} // Print
