/**
 * generated by Xtext 2.25.0
 */
package org.xtext.idmProject.iDMProject.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.idmProject.iDMProject.ArrayObject;
import org.xtext.idmProject.iDMProject.BooleanObject;
import org.xtext.idmProject.iDMProject.Final;
import org.xtext.idmProject.iDMProject.IDMProjectFactory;
import org.xtext.idmProject.iDMProject.IDMProjectPackage;
import org.xtext.idmProject.iDMProject.Initialisation;
import org.xtext.idmProject.iDMProject.Insert;
import org.xtext.idmProject.iDMProject.JsonCommand;
import org.xtext.idmProject.iDMProject.JsonCommands;
import org.xtext.idmProject.iDMProject.JsonEntries;
import org.xtext.idmProject.iDMProject.JsonEntry;
import org.xtext.idmProject.iDMProject.JsonObject;
import org.xtext.idmProject.iDMProject.JsonPrimitive;
import org.xtext.idmProject.iDMProject.Modify;
import org.xtext.idmProject.iDMProject.Mult;
import org.xtext.idmProject.iDMProject.Operation;
import org.xtext.idmProject.iDMProject.Path;
import org.xtext.idmProject.iDMProject.Print;
import org.xtext.idmProject.iDMProject.Remove;
import org.xtext.idmProject.iDMProject.Select;
import org.xtext.idmProject.iDMProject.Store;
import org.xtext.idmProject.iDMProject.StringObject;
import org.xtext.idmProject.iDMProject.Sum;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class IDMProjectFactoryImpl extends EFactoryImpl implements IDMProjectFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static IDMProjectFactory init()
  {
    try
    {
      IDMProjectFactory theIDMProjectFactory = (IDMProjectFactory)EPackage.Registry.INSTANCE.getEFactory(IDMProjectPackage.eNS_URI);
      if (theIDMProjectFactory != null)
      {
        return theIDMProjectFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new IDMProjectFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IDMProjectFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case IDMProjectPackage.JSON_COMMANDS: return createJsonCommands();
      case IDMProjectPackage.JSON_COMMAND: return createJsonCommand();
      case IDMProjectPackage.INITIALISATION: return createInitialisation();
      case IDMProjectPackage.OPERATION: return createOperation();
      case IDMProjectPackage.INSERT: return createInsert();
      case IDMProjectPackage.PATH: return createPath();
      case IDMProjectPackage.MODIFY: return createModify();
      case IDMProjectPackage.SUM: return createSum();
      case IDMProjectPackage.REMOVE: return createRemove();
      case IDMProjectPackage.MULT: return createMult();
      case IDMProjectPackage.SELECT: return createSelect();
      case IDMProjectPackage.FINAL: return createFinal();
      case IDMProjectPackage.STORE: return createStore();
      case IDMProjectPackage.PRINT: return createPrint();
      case IDMProjectPackage.JSON_OBJECT: return createJsonObject();
      case IDMProjectPackage.JSON_PRIMITIVE: return createJsonPrimitive();
      case IDMProjectPackage.ARRAY_OBJECT: return createArrayObject();
      case IDMProjectPackage.BOOLEAN_OBJECT: return createBooleanObject();
      case IDMProjectPackage.STRING_OBJECT: return createStringObject();
      case IDMProjectPackage.JSON_ENTRIES: return createJsonEntries();
      case IDMProjectPackage.JSON_ENTRY: return createJsonEntry();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case IDMProjectPackage.BOOLEAN:
        return createBooleanFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case IDMProjectPackage.BOOLEAN:
        return convertBooleanToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonCommands createJsonCommands()
  {
    JsonCommandsImpl jsonCommands = new JsonCommandsImpl();
    return jsonCommands;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonCommand createJsonCommand()
  {
    JsonCommandImpl jsonCommand = new JsonCommandImpl();
    return jsonCommand;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Initialisation createInitialisation()
  {
    InitialisationImpl initialisation = new InitialisationImpl();
    return initialisation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operation createOperation()
  {
    OperationImpl operation = new OperationImpl();
    return operation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Insert createInsert()
  {
    InsertImpl insert = new InsertImpl();
    return insert;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Path createPath()
  {
    PathImpl path = new PathImpl();
    return path;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Modify createModify()
  {
    ModifyImpl modify = new ModifyImpl();
    return modify;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Sum createSum()
  {
    SumImpl sum = new SumImpl();
    return sum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Remove createRemove()
  {
    RemoveImpl remove = new RemoveImpl();
    return remove;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Mult createMult()
  {
    MultImpl mult = new MultImpl();
    return mult;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Select createSelect()
  {
    SelectImpl select = new SelectImpl();
    return select;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Final createFinal()
  {
    FinalImpl final_ = new FinalImpl();
    return final_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Store createStore()
  {
    StoreImpl store = new StoreImpl();
    return store;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Print createPrint()
  {
    PrintImpl print = new PrintImpl();
    return print;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonObject createJsonObject()
  {
    JsonObjectImpl jsonObject = new JsonObjectImpl();
    return jsonObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonPrimitive createJsonPrimitive()
  {
    JsonPrimitiveImpl jsonPrimitive = new JsonPrimitiveImpl();
    return jsonPrimitive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ArrayObject createArrayObject()
  {
    ArrayObjectImpl arrayObject = new ArrayObjectImpl();
    return arrayObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanObject createBooleanObject()
  {
    BooleanObjectImpl booleanObject = new BooleanObjectImpl();
    return booleanObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StringObject createStringObject()
  {
    StringObjectImpl stringObject = new StringObjectImpl();
    return stringObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonEntries createJsonEntries()
  {
    JsonEntriesImpl jsonEntries = new JsonEntriesImpl();
    return jsonEntries;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonEntry createJsonEntry()
  {
    JsonEntryImpl jsonEntry = new JsonEntryImpl();
    return jsonEntry;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public org.xtext.idmProject.iDMProject.Boolean createBooleanFromString(EDataType eDataType, String initialValue)
  {
    org.xtext.idmProject.iDMProject.Boolean result = org.xtext.idmProject.iDMProject.Boolean.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertBooleanToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IDMProjectPackage getIDMProjectPackage()
  {
    return (IDMProjectPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static IDMProjectPackage getPackage()
  {
    return IDMProjectPackage.eINSTANCE;
  }

} //IDMProjectFactoryImpl
