/**
 * generated by Xtext 2.25.0
 */
package org.xtext.idmProject.iDMProject.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.idmProject.iDMProject.IDMProjectPackage;
import org.xtext.idmProject.iDMProject.JsonPrimitive;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Json Primitive</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class JsonPrimitiveImpl extends JsonObjectImpl implements JsonPrimitive
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JsonPrimitiveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IDMProjectPackage.Literals.JSON_PRIMITIVE;
  }

} //JsonPrimitiveImpl
