/**
 * generated by Xtext 2.25.0
 */
package org.xtext.idmProject.iDMProject.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.idmProject.iDMProject.IDMProjectPackage;
import org.xtext.idmProject.iDMProject.JsonCommand;
import org.xtext.idmProject.iDMProject.JsonCommands;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Json Commands</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.idmProject.iDMProject.impl.JsonCommandsImpl#getJsonCommands <em>Json Commands</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JsonCommandsImpl extends MinimalEObjectImpl.Container implements JsonCommands
{
  /**
   * The cached value of the '{@link #getJsonCommands() <em>Json Commands</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJsonCommands()
   * @generated
   * @ordered
   */
  protected EList<JsonCommand> jsonCommands;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JsonCommandsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IDMProjectPackage.Literals.JSON_COMMANDS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<JsonCommand> getJsonCommands()
  {
    if (jsonCommands == null)
    {
      jsonCommands = new EObjectContainmentEList<JsonCommand>(JsonCommand.class, this, IDMProjectPackage.JSON_COMMANDS__JSON_COMMANDS);
    }
    return jsonCommands;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IDMProjectPackage.JSON_COMMANDS__JSON_COMMANDS:
        return ((InternalEList<?>)getJsonCommands()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IDMProjectPackage.JSON_COMMANDS__JSON_COMMANDS:
        return getJsonCommands();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IDMProjectPackage.JSON_COMMANDS__JSON_COMMANDS:
        getJsonCommands().clear();
        getJsonCommands().addAll((Collection<? extends JsonCommand>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IDMProjectPackage.JSON_COMMANDS__JSON_COMMANDS:
        getJsonCommands().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IDMProjectPackage.JSON_COMMANDS__JSON_COMMANDS:
        return jsonCommands != null && !jsonCommands.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //JsonCommandsImpl
