/**
 * generated by Xtext 2.25.0
 */
package org.xtext.idmProject.iDMProject.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.idmProject.iDMProject.IDMProjectPackage;
import org.xtext.idmProject.iDMProject.JsonObject;
import org.xtext.idmProject.iDMProject.Modify;
import org.xtext.idmProject.iDMProject.Path;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Modify</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.idmProject.iDMProject.impl.ModifyImpl#getPath <em>Path</em>}</li>
 *   <li>{@link org.xtext.idmProject.iDMProject.impl.ModifyImpl#getJsonObject <em>Json Object</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModifyImpl extends OperationImpl implements Modify
{
  /**
   * The cached value of the '{@link #getPath() <em>Path</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPath()
   * @generated
   * @ordered
   */
  protected Path path;

  /**
   * The cached value of the '{@link #getJsonObject() <em>Json Object</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJsonObject()
   * @generated
   * @ordered
   */
  protected JsonObject jsonObject;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModifyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IDMProjectPackage.Literals.MODIFY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Path getPath()
  {
    return path;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPath(Path newPath, NotificationChain msgs)
  {
    Path oldPath = path;
    path = newPath;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IDMProjectPackage.MODIFY__PATH, oldPath, newPath);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPath(Path newPath)
  {
    if (newPath != path)
    {
      NotificationChain msgs = null;
      if (path != null)
        msgs = ((InternalEObject)path).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IDMProjectPackage.MODIFY__PATH, null, msgs);
      if (newPath != null)
        msgs = ((InternalEObject)newPath).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IDMProjectPackage.MODIFY__PATH, null, msgs);
      msgs = basicSetPath(newPath, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDMProjectPackage.MODIFY__PATH, newPath, newPath));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonObject getJsonObject()
  {
    return jsonObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetJsonObject(JsonObject newJsonObject, NotificationChain msgs)
  {
    JsonObject oldJsonObject = jsonObject;
    jsonObject = newJsonObject;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IDMProjectPackage.MODIFY__JSON_OBJECT, oldJsonObject, newJsonObject);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJsonObject(JsonObject newJsonObject)
  {
    if (newJsonObject != jsonObject)
    {
      NotificationChain msgs = null;
      if (jsonObject != null)
        msgs = ((InternalEObject)jsonObject).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IDMProjectPackage.MODIFY__JSON_OBJECT, null, msgs);
      if (newJsonObject != null)
        msgs = ((InternalEObject)newJsonObject).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IDMProjectPackage.MODIFY__JSON_OBJECT, null, msgs);
      msgs = basicSetJsonObject(newJsonObject, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDMProjectPackage.MODIFY__JSON_OBJECT, newJsonObject, newJsonObject));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IDMProjectPackage.MODIFY__PATH:
        return basicSetPath(null, msgs);
      case IDMProjectPackage.MODIFY__JSON_OBJECT:
        return basicSetJsonObject(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IDMProjectPackage.MODIFY__PATH:
        return getPath();
      case IDMProjectPackage.MODIFY__JSON_OBJECT:
        return getJsonObject();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IDMProjectPackage.MODIFY__PATH:
        setPath((Path)newValue);
        return;
      case IDMProjectPackage.MODIFY__JSON_OBJECT:
        setJsonObject((JsonObject)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IDMProjectPackage.MODIFY__PATH:
        setPath((Path)null);
        return;
      case IDMProjectPackage.MODIFY__JSON_OBJECT:
        setJsonObject((JsonObject)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IDMProjectPackage.MODIFY__PATH:
        return path != null;
      case IDMProjectPackage.MODIFY__JSON_OBJECT:
        return jsonObject != null;
    }
    return super.eIsSet(featureID);
  }

} //ModifyImpl
