/**
 * generated by Xtext 2.25.0
 */
package org.xtext.idmProject.iDMProject.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.idmProject.iDMProject.IDMProjectPackage;
import org.xtext.idmProject.iDMProject.Mult;
import org.xtext.idmProject.iDMProject.Path;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Mult</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.idmProject.iDMProject.impl.MultImpl#getPathTOStore <em>Path TO Store</em>}</li>
 *   <li>{@link org.xtext.idmProject.iDMProject.impl.MultImpl#getPathToMult <em>Path To Mult</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MultImpl extends OperationImpl implements Mult
{
  /**
   * The cached value of the '{@link #getPathTOStore() <em>Path TO Store</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPathTOStore()
   * @generated
   * @ordered
   */
  protected Path pathTOStore;

  /**
   * The cached value of the '{@link #getPathToMult() <em>Path To Mult</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPathToMult()
   * @generated
   * @ordered
   */
  protected Path pathToMult;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MultImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IDMProjectPackage.Literals.MULT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Path getPathTOStore()
  {
    return pathTOStore;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPathTOStore(Path newPathTOStore, NotificationChain msgs)
  {
    Path oldPathTOStore = pathTOStore;
    pathTOStore = newPathTOStore;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IDMProjectPackage.MULT__PATH_TO_STORE, oldPathTOStore, newPathTOStore);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPathTOStore(Path newPathTOStore)
  {
    if (newPathTOStore != pathTOStore)
    {
      NotificationChain msgs = null;
      if (pathTOStore != null)
        msgs = ((InternalEObject)pathTOStore).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IDMProjectPackage.MULT__PATH_TO_STORE, null, msgs);
      if (newPathTOStore != null)
        msgs = ((InternalEObject)newPathTOStore).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IDMProjectPackage.MULT__PATH_TO_STORE, null, msgs);
      msgs = basicSetPathTOStore(newPathTOStore, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDMProjectPackage.MULT__PATH_TO_STORE, newPathTOStore, newPathTOStore));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Path getPathToMult()
  {
    return pathToMult;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPathToMult(Path newPathToMult, NotificationChain msgs)
  {
    Path oldPathToMult = pathToMult;
    pathToMult = newPathToMult;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IDMProjectPackage.MULT__PATH_TO_MULT, oldPathToMult, newPathToMult);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPathToMult(Path newPathToMult)
  {
    if (newPathToMult != pathToMult)
    {
      NotificationChain msgs = null;
      if (pathToMult != null)
        msgs = ((InternalEObject)pathToMult).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IDMProjectPackage.MULT__PATH_TO_MULT, null, msgs);
      if (newPathToMult != null)
        msgs = ((InternalEObject)newPathToMult).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IDMProjectPackage.MULT__PATH_TO_MULT, null, msgs);
      msgs = basicSetPathToMult(newPathToMult, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDMProjectPackage.MULT__PATH_TO_MULT, newPathToMult, newPathToMult));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IDMProjectPackage.MULT__PATH_TO_STORE:
        return basicSetPathTOStore(null, msgs);
      case IDMProjectPackage.MULT__PATH_TO_MULT:
        return basicSetPathToMult(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IDMProjectPackage.MULT__PATH_TO_STORE:
        return getPathTOStore();
      case IDMProjectPackage.MULT__PATH_TO_MULT:
        return getPathToMult();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IDMProjectPackage.MULT__PATH_TO_STORE:
        setPathTOStore((Path)newValue);
        return;
      case IDMProjectPackage.MULT__PATH_TO_MULT:
        setPathToMult((Path)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IDMProjectPackage.MULT__PATH_TO_STORE:
        setPathTOStore((Path)null);
        return;
      case IDMProjectPackage.MULT__PATH_TO_MULT:
        setPathToMult((Path)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IDMProjectPackage.MULT__PATH_TO_STORE:
        return pathTOStore != null;
      case IDMProjectPackage.MULT__PATH_TO_MULT:
        return pathToMult != null;
    }
    return super.eIsSet(featureID);
  }

} //MultImpl
