/*
 * generated by Xtext 2.25.0
 */
package org.xtext.idmProject.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class IDMProjectUiModule extends AbstractIDMProjectUiModule {

	public IDMProjectUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
