/*
 * generated by Xtext 2.25.0
 */
package org.xtext.idmProject.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.idmProject.ui.internal.IdmProjectActivator;

public class IDMProjectUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IdmProjectActivator.getInstance().getInjector("org.xtext.idmProject.IDMProject");
	}

}
