/*
 * generated by Xtext 2.25.0
 */
package org.xtext.idmProject.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractIDMProjectValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.idmProject.iDMProject.IDMProjectPackage.eINSTANCE);
		return result;
	}
}
