/*
 * generated by Xtext 2.25.0
 */
package org.xtext.idmProject.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.idmProject.ui.internal.IdmProjectActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IDMProjectExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(IdmProjectActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		IdmProjectActivator activator = IdmProjectActivator.getInstance();
		return activator != null ? activator.getInjector(IdmProjectActivator.ORG_XTEXT_IDMPROJECT_IDMPROJECT) : null;
	}

}
